FIWARELabNodesSLA script added
martel-innovate/join-fiware-lab-guide pull request #4
Opened 2017-12-07 11:25 UTC by K4s14

2018-02-02 15:59 UTC, chicco785 requested changes
Hi @K4s14 i made few specific comments, additionally:
* use MD syntax for README.org -> README.md (to be uniform)
* apply an MD linter to check formatting and limit lines to 80 chars.

2018-02-02 15:59 UTC, chicco785 commented on scripts/FIWARELabNodesSLA/README.org
> +  The nodes, that are funded by the FI-NEXT project, have to assure a certain level of quality defined through a Service Level Agreement (SLA). One of the conditions that must be satisfied is the ser
The nodes taking part to FIWARE Lab have to assure a certain level of quality defined through a Service Level Agreement (SLA). One of the conditions that must be satisfied is the services availability on the node that must be above the 95% threshold.\\

2018-02-02 15:59 UTC, chicco785 commented on scripts/FIWARELabNodesSLA/README.org
> +  FIWARE relies on the above pipeline to calculate the FIWARE Lab node overall service availability analysing the uptime status of:
FIWARE Lab Admins rely on the above pipeline to calculate the FIWARE Lab node overall service availability analysing the uptime status of:

2018-02-09 13:46 UTC, K4s14 reviewed
I think the README file should be in the correct format now. I changed also the text you suggested.

2018-02-09 14:55 UTC, chicco785 approved these changes
minor fixes, i believe that after that we can merge

2018-02-09 14:55 UTC, chicco785 commented on scripts/FIWARELabNodesSLA/README.md
> +1) optional arguments:
1.

2018-02-09 14:55 UTC, chicco785 commented on scripts/FIWARELabNodesSLA/README.md
> +    - -h, --help: shows the help message and exit
use code syntax for the parameters

2018-02-09 14:55 UTC, chicco785 commented on scripts/FIWARELabNodesSLA/README.md
> +
1.

2018-02-09 14:55 UTC, chicco785 commented on scripts/FIWARELabNodesSLA/README.md
> +  ```bash
increase indent of the code so that is aligned with the list

2018-02-09 19:12 UTC, merged